language: "perl"

perl:
  - "5.14"

env:
  - COVERALLS=true  DB=mysql
  
sudo: false
  
addons:
  apt:
    packages:
    - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - wget https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-2-3.zip
    - unzip bioperl-release-1-2-3.zip

install:
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp travisci/MultiTestDB.conf.travisci.mysql  t/MultiTestDB.conf.mysql
    - cd ensembl && cpanm -v --installdeps .
    - cd -

script: "./travisci/harness.sh"


notifications:
  email:
    on_success: always
    on_failure: always
  notifications:
    slack: genomes-ebi:ZVN9oaY6GQ7HDSBtmQC5f5PL
