language: "perl"

perl:
  - "5.14"

env:
  - COVERALLS=true  DB=mysql
  
sudo: false
  
addons:
  apt:
    packages:
    - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-hive.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - wget https://github.com/bioperl/bioperl-live/archive/release-1-6-924.zip
    - unzip release-1-6-924.zip

install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm -v --installdeps --notest --cpanfile ensembl-hive/cpanfile .
    - cpanm -v --installdeps --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp travisci/MultiTestDB.conf.travisci.mysql  t/MultiTestDB.conf.mysql

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
  notifications:
    slack: genomes-ebi:ZVN9oaY6GQ7HDSBtmQC5f5PL
